### ISSUE TITLE
Vector to Text inversion using MPS/CPU

### ISSUE THREAD

**Issue by hyungkwonko** [jxmorris12/vec2text#23]
Hi, Thanks for great work. I have realized that inverting vector to text is only possible using CUDA. Is there any way I can do this using MPS/CPU? I am using Macbook (Intel). Thanks.

The error I get is:
```
RuntimeError: Placeholder storage has not been allocated on MPS device!
```

**Comment by jxmorris12** [comment]
Merry Christmas. I think MPS usage is exactly what this unfinished pull request is intended to support. Feel free to try it out: https://github.com/jxmorris12/vec2text/pull/17

**Comment by hyungkwonko** [comment]
Thanks a lot Jack. It works well. Hope you have a happy holiday.

Best,
Kwon
