### ISSUE TITLE
Add mps support

### ISSUE THREAD

**Issue by NMontanaBrown** [jxmorris12/vec2text#3]
# Issue Description

MPS device support could be added by checking for "mps" availability prior to assigning to "cpu" by changing conditional statement here:

https://github.com/jxmorris12/vec2text/blob/b121c689402b16728d4aa71362c2eac4374c1c26/vec2text/models/model_utils.py#L36

**Comment by jxmorris12** [comment]
LGTM! Thanks! Now people should be able to run this on their Mac, I think!
