### ISSUE TITLE
Why padding all text to max length in  trainer.base. _get_decoded_sequences

### ISSUE THREAD

**Issue by liyongkang123** [jxmorris12/vec2text#37]
Hi John, Thanks for your great work.

I would like to know why you are padding both the generated text and true_input_ids to the maximum length in the _get_decoded_sequences function. Is this operation necessary for later evaluation calculations?

Thank you for your help!

**Comment by jxmorris12** [comment]
I think it was so that we could keep a list of the "best text seen so far", in case the length changed between generations, so that everything can be stacked into the same-sized list. I think you can disable this if you're not using that feature.

**Comment by liyongkang123** [comment]
Got it! Thanks a lot~
