### ISSUE TITLE
Using Initial Inversion Model Only

### ISSUE THREAD

**Issue by VMS-6511** [jxmorris12/vec2text#46]
If I was looking to just look at inverting the text with the initial inversion model without the corrector would it be sufficient to simply pass that model as the corrector itself to the API? Thanks!

**Comment by jxmorris12** [comment]
Good question! I think the simplest way is actually to just set `num_steps=0` and then [under the hood](https://github.com/jxmorris12/vec2text/blob/master/vec2text/trainers/corrector.py#L306) the corrector won't be called at all.

**Comment by VMS-6511** [comment]
What if I haven't trained a corrector model?

**Comment by jxmorris12** [comment]
Sorry – are you trying to just use your own model that you've trained? Then you need to use `analyze_utils.load_experiment_and_trainer_from_pretrained` and then `trainer.generate()` or `trainer.evaluate()` but that should work fine.

**Comment by VMS-6511** [comment]
Sorry yeah what I'm trying to do is a I trained my own zero step inversion model. Now I'd like to pass embeddings to that model and get the corresponding inverted text back.

**Comment by VMS-6511** [comment]
Okay so I tried doing that but I'm encountering this error:

`ModuleNotFoundError: No module named 'run_args'`

**Comment by jxmorris12** [comment]
sorry -- do you mind filing a new issue with a full stack trace? That command runs for me. I tried it yesterday in colab.

**Comment by VMS-6511** [comment]
I got it working sorry for the confusion it was an issue with finding the right path.
