### ISSUE TITLE
Need "llama_unigram.pt" to load "jxm/t5-base___llama-7b___one-million-instructions__correct"

### ISSUE THREAD

**Issue by tiandong1234** [jxmorris12/vec2text#65]
Hi, when loading "jxm/t5-base___llama-7b___one-million-instructions__correct"  model, it appears that I need the file "/home/jxm3/research/retrieval/inversion/llama_unigram.pt" . Could you please release this file? Or tell me how to generate this file?

**Comment by jxmorris12** [comment]
Hi @tiandong1234 – I've removed this constraint. Can you try running the code from the latest branch?

**Comment by tiandong1234** [comment]
> Hi @tiandong1234 – I've removed this constraint. Can you try running the code from the latest branch?

It's working now. I have a small suggestion for improvement: if someone like me loads the LLM model from a local path, the function load_embedder_and_tokenizer in the file model_utils.py might not correctly identify the model type. Could you add a parameter or argparse option that allows users to specify the model type?

**Comment by jxmorris12** [comment]
@tiandong1234 Can you give an example of what this would look like? Also, feel free to submit a pull request.
