### ISSUE TITLE
Access to GTR model

### ISSUE THREAD

**Issue by phubbard** [jxmorris12/vec2text#7]
In the readme and the code, I see that the GTR inverter is by request. I didn't find another way to contact the authors, so could you please let me know how I could get the second inverter? Thank you.

**Comment by kyriemao** [comment]
Hi Morris, thanks for your great work! I have the same request for the GTR inverter checkpoint. Could you provide that?

**Comment by phubbard** [comment]
Got it. Don’t bother if I’m the only one who’s asked.

**Comment by jxmorris12** [comment]
Hi @phubbard -- I trained a single-step inversion model for 128-length GTR embeddings here: https://huggingface.co/jxm/gtr__msmarco__128

We now need compute to use this model to train the correction model. Then I can add the GTR inverter to vec2text so it's easy to use through the API.

As an aside, is anyone looking for the 32-length model we used in the paper? That one would need to be trained separately (although it converges much more quickly). 

Finally, here's my relevant comment on the similar issue about SBERT models: https://github.com/jxmorris12/vec2text/issues/5#issuecomment-1787173530

**Comment by kyriemao** [comment]
> Hi @phubbard -- I trained a single-step inversion model for 128-length GTR embeddings here: https://huggingface.co/jxm/gtr__msmarco__128
> 
> We now need compute to use this model to train the correction model. Then I can add the GTR inverter to vec2text so it's easy to use through the API.
> 
> As an aside, is anyone looking for the 32-length model we used in the paper? That one would need to be trained separately (although it converges much more quickly).
> 
> Finally, here's my relevant comment on the similar issue about SBERT models: [#5 (comment)](https://github.com/jxmorris12/vec2text/issues/5#issuecomment-1787173530)

Hi Morris, I need that 32 length GTR model, could you please provide it？

**Comment by jxmorris12** [comment]
@kyriemao yep -- that one's much less computationally expensive. I'll train a final version and upload it ASAP. The sequence-length 128 model will take more effort and many more FLOPS...

**Comment by jxmorris12** [comment]
@kyriemao yep -- that one's much less computationally expensive. I'll train a final version and upload it ASAP. The sequence-length 128 model will take more effort and many more FLOPS...

**Comment by jxmorris12** [comment]
Hi @kyriemao -- I uploaded the sequence-length 32 GTR inverter; see "Evaluate the model from the paper" in the README.

**Comment by kyriemao** [comment]
> Hi @kyriemao -- I uploaded the sequence-length 32 GTR inverter; see "Evaluate the model from the paper" in the README.

Thank you very much!

**Comment by jkurlandski01** [comment]
When I try to run the code in the "Evaluate the model from the paper" section in the README, I get an error:
```
AttributeError                            Traceback (most recent call last)
[<ipython-input-18-3e478b6f2c51>](https://localhost:8080/#) in <cell line: 7>()
      5 
      6 # experiment, trainer = analyze_utils.load_experiment_and_trainer_from_pretrained(
----> 7 experiment, trainer = a_utils.load_experiment_and_trainer_from_pretrained(    
      8      "jxm/gtr__nq__32__correct"
      9 )

AttributeError: module 'vec2text.analyze_utils' has no attribute 'load_experiment_and_trainer_from_pretrained'
```

I'm not sure if this is relevant, but when I call `dir(analyze_utils)` the result does not include any functions from analyze_utils.py which occur after the definition of load_results_from_folder( ).
```
['DataArguments',
 'HfArgumentParser',
 'ModelArguments',
 'Optional',
 'TrainingArguments',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'device',
 'experiments',
 'get_last_checkpoint',
 'glob',
 'json',
 'load_experiment_and_trainer',
 'load_results_from_folder',
 'load_trainer',
 'os',
 'pd',
 'shlex',
 'torch',
 'transformers']
```

**Comment by jxmorris12** [comment]
@jkurlandski01 thanks for reporting. I'm guessing you're behind main? Can you try doing a git pull (or new pip install) and let me know if that code still doesn't work?

**Comment by jkurlandski01** [comment]
Thanks! I no longer get that error.
