### ISSUE TITLE
Generated text length problem

### ISSUE THREAD

**Issue by pijiawei** [jxmorris12/vec2text#71]
When I created a new text for testing, I found that when the sentence length reached a certain level, the generated text would be truncated midway. What is the reason for this?
![1](https://github.com/user-attachments/assets/d60182d1-8bd8-424b-a3d0-554bd11f262a)

**Comment by jxmorris12** [comment]
Hi @pijiawei – I think this is because our model maximum output length is 128 tokens, and you're hitting that limit.

**Comment by pijiawei** [comment]
> Hi @pijiawei – I think this is because our model maximum output length is 128 tokens, and you're hitting that limit.

Thank you
