### ISSUE TITLE
OpenAI tokens requirement

### ISSUE THREAD

**Issue by mursaleen5336** [jxmorris12/vec2text#74]
Is there any tokens quota requirement mention to run the code with pre-trained model?

![WhatsApp Image 2024-11-18 at 23 35 27_0510d004](https://github.com/user-attachments/assets/156de1e6-8fe6-4c54-83fa-9e19ac8a5193)

**Comment by jxmorris12** [comment]
This error means you need to sign up and make an account to use the OpenAI API: https://platform.openai.com/docs/guides/rate-limits
