### ISSUE TITLE
Missing important refs in the paper.

### ISSUE THREAD

**Issue by MorinoCheng** [jxmorris12/vec2text#9]
Hello John!
Congratulations on your nice work that inverts OpenAI embeddings to texts. I just would like you to notice that there is a missing ref in your manuscript. The work is probably one of the earliest works which study the privacy risks of LLM embeddings (also cited by [Song et al.; 2020]). 

Pan X, Zhang M, Ji S, et al. Privacy risks of general-purpose language models[C]//2020 IEEE Symposium on Security and Privacy (SP). IEEE, 2020: 1314-1331.

Hope the information can help.

Morino

**Comment by jxmorris12** [comment]
Hi, thanks for letting me know. I don't know if I'd say the paper is definitively a 'missing' reference – I think there are many papers at about this level of relevance – but it certainly is interesting and related and I'm surprised I hadn't seen it before. It's great work. Thanks for sharing; I'll keep it in mind for future work or if I ever update the manuscript for the current paper.
